### ISSUE TITLE
"Aplica" button for the last job is missing on the results page

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/androidAPP#3]
apk V1
Device: Laptop
OS: Windows 11, BlueStacks 10

**STEPS TO REPRODUCE:**

1. Open the peviitor apk
2. Search for "bucatar"
3. Scroll down and observe that the last job has no "Aplica" button.

**EXPECTED RESULTS:**
Every job should have a "Aplica" button.

**ACTUAL RESULTS:**
The last job from the results page has no "Aplica" button.

![image](https://github.com/user-attachments/assets/f56bf066-6ee2-4229-86c2-d10ceaeb03b8)

**Comment by lalalaurentiu** [comment]
Fixed please retest in version [1.3.3](https://expo.dev/artifacts/eas/86W92kQB1zouAru19i1XDG.apk)

**Comment by Florin201092** [comment]
FIXED!
