### ISSUE TITLE
[mobile-Moto g84 G5] Incorrect Display of the Upper Part of the Background 

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/androidAPP#5]
**ENVIRONMENT**: 
  - url: [apk v1](https://expo.dev/artifacts/eas/f3qjkwoLgX3yCSMeUhAdT.apk)
  - browser: Chrome
  - operating system: Android
  - telephone type: moto g84 G5

**STEPS TO REPRODUCE**: 
1. Open [apk v1.](https://expo.dev/artifacts/eas/f3qjkwoLgX3yCSMeUhAdT.apk)
2. Check visually that the upper part of the background is displayed correctly. 

**EXPECTED RESULTS**:
1. The upper part of the background is displayed correctly. 

**ACTUAL RESULTS**:
1. The upper part of the background is not displayed correctly. 

![image](https://github.com/user-attachments/assets/5bbe573e-b3f5-41e3-986a-ff114a39b044)

**Comment by lalalaurentiu** [comment]
Fixed please retest in version [1.3.3](https://expo.dev/artifacts/eas/86W92kQB1zouAru19i1XDG.apk)

**Comment by Lore78** [comment]
The bug was tested in version 1.3.3 and it is fixed.
