### ISSUE TITLE
[mobile-Moto g84 G5] Incorrect Language used for the Footer Section on the Main Page

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/androidAPP#6]
**ENVIRONMENT**: 
  - url:  [apk v1.2](https://expo.dev/artifacts/eas/f3qjkwoLgX3yCSMeUhAdT.apk)
  - browser: Chrome
  - operating system: Android
  - telephone type: moto g84 G5

**STEPS TO REPRODUCE**: 
1. Open  [apk v1.2](https://expo.dev/artifacts/eas/f3qjkwoLgX3yCSMeUhAdT.apk)
2. Check visually that the footer section is displayed correctly.

**EXPECTED RESULTS**:
1. The footer is displayed correctly.

**ACTUAL RESULTS**:
1. The two sections in the footer "Home" and "Results" are written in English, unlike the other information on the page.

![image](https://github.com/user-attachments/assets/92a96df7-8a25-427d-bde6-ea007ee8af22)

**Comment by lalalaurentiu** [comment]
Fixed please retest in version [1.3.3](https://expo.dev/artifacts/eas/86W92kQB1zouAru19i1XDG.apk)

**Comment by Lore78** [comment]
The bug was tested in version 1.3.3 and it is fixed.

![image](https://github.com/user-attachments/assets/dd75b339-6bcd-446d-8b29-49b875b26c3f)
